name: my_own_flashcard_v0
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0
  path_provider:
  path:
  toast: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  moor_generator: ^3.3.1
  # analyzer: ^0.40.2

# for "Bad state: Unexpected diagnostics"
# dependency_overrides:
#   analyzer: '0.39.14'
  # analyzer: ^0.40.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    # ファミリーはLanobeでも何でも良い
    - family: Lanobe
      fonts:
        - asset: assets/fonts/lanobe_pop.otf
    - family: Mont
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
